apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-pipeline-run-
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: sample-pipeline
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: slow-listener
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: remove-me-listener
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template

