apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: echo-listener-bg
spec:
  triggers:
    - binding:
        name: echo-pipeline-binding-bg
      template:
        name: echo-pipeline-template-bg
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: echo-pipeline-binding-bg
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: echo-pipeline-template-bg
spec:
  params:
    - name: env
      description: Env property
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: consumption-monitor-run-
        labels:
          triggertemplated: "true"
          generatedBy: "echo-example-bg"
      spec:
        pipelineRef:
          name: echo-props-pipeline-bg
        params:
          - name: env
            value: $(params.env)  
