---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: normal-pipelinerun-
spec:
  pipelineSpec:
    tasks:
    - name: normal-task1
      taskSpec:
        steps:
        - name: normal-task1-step1
          image: centos
          command: ["bash", "-c"]
          args:
            - echo "=======================";
              echo "Task1";
              echo "=======================";
              echo "IBM Cloud - Status - https://cloud.ibm.com";
              echo "=======================";
              sleep 10;
              alive=$(curl -s -o /dev/null -L -w %{http_code} https://cloud.ibm.com);
              if [ "$alive" == "200" ];
              then echo "TEST PASS - 200"; exit 0;
              else echo "TEST FAIL - $alive"; exit 1;
              fi
    - name: normal-task2
      taskSpec:
        steps:
        - name: normal-task2-step1
          image: centos
          command: ["bash", "-c"]
          args:
            - echo "=======================";
              echo "Task2";
              echo "=======================";
              echo "IBM.com - Status - https://ibm.com";
              echo "=======================";
              sleep 10;
              alive=$(curl -s -o /dev/null -L -w %{http_code} https://ibm.com);
              if [ "$alive" == "200" ];
              then echo "TEST PASS - 200"; exit 0;
              else echo "TEST FAIL - $alive"; exit 1;
              fi