---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bundle-pipeline
spec:
  tasks:
  - name: my-task1
    taskRef:
      name: bundle-task1
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bundle-task1
spec:
  steps:
  - name: task-one-step-one
    image: centos
    command: ["bash", "-c"]
    args:
      - echo "=======================";
        echo "Bundle Task1";
        echo "=======================";
        echo "IBM Cloud - Status - https://cloud.ibm.com";
        echo "=======================";
        sleep 10;
        alive=$(curl -s -o /dev/null -L -w %{http_code} https://cloud.ibm.com);
        if [ "$alive" == "200" ];
        then echo "TEST PASS - 200"; exit 0;
        else echo "TEST FAIL - $alive"; exit 1;
        fi