---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sample-pipelinerun-
spec:
  pipelineRef:
    name: bundle-pipeline
    bundle: index.docker.io/beglee/pipelinebundle@sha256:36616e48b3429187a027fd52a44152548a3211b61e4be60efbf83cb85d43b904
  params: []