apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: echo-props-pipeline-bg
spec:
  params:
    - name: test
      description: simple test property
      default: TEST
    - name: env
      description: env property
  tasks:
    - name: show-build-number-bg
      taskRef:
        name: simple-task-bg
    - name: echo-task-bg
      taskRef:
        name: echo-props-bg
      params:
        - name: env
          value: $(params.env)
    - name: echo-env-bg
      taskRef:
        name: env-prop-from-config-bg
