apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  steps:
    - name: simple-step
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
      command: ["bash", "-c"]
      args:
        - echo $BUILD_NUMBER;   
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-props
spec:
  params:
    - name: environment_value
      description: Value from pipeline, trigger, or run property    
  steps:
    - name: show-props
      image: ubuntu
      env:
        - name: ENVIRONMENT_VALUE
          value: $(params.environment_value)  
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']  
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "The \033[36menvironment\033[0m value from properties is >>";
          echo $ENVIRONMENT_VALUE
          sleep 30
          echo "$BUILD_NUMBER Complete";
